[project]
name = "ip-addr-dl-mgr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipaddress>=1.0.23",
    "pandas>=2.2.3",
]
